version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase..
  build:
    commands:
      - echo Build started on `23/8/22`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `23/8/22`
artifacts:
  type: zip
  paths:
    - target/*.jar
